### PR TITLE
support usdc new listing and bid

### PR DESCRIPTION
**Pull request by mchigit**
Still lots of clean up is needed, but I think this PR should get USDC listing and bid working.

### CODE REVIEW

**Comment by ryanprice** [comment]
Switched wallets
new listing added with 5 USDC as min. bid
confirmed MM. got this

image

**Comment by mchigit** [comment]
yah the duplicated listing and events should be fixed here: https://github.com/Cardinal-Entertainment/nft-market/pull/222

I did also find a bug with buying an instant auction doesn't make that listing as "Ended". Opened an issue to keep track: https://github.com/Cardinal-Entertainment/api-zoombies-world/issues/29

**Comment by mchigit** [comment]
Will look into the listing price. Probably one of things that needs to be cleaned up 😅

**Comment by ryanprice** [comment]
Moonriver Auction num. 13 on the contract says the highest current bid is 4000000. Maybe the server is not scraping the correct info ?

**Review by ryanprice — APPROVED** [review]
works !

**Pull request merged**
